// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wework/crypto.go
//
// Generated by this command:
//
//	mockgen -source=internal/wework/crypto.go -destination=internal/wework/mock_crypto.go -package=wework
//

// Package wework is a generated GoMock package.
package wework

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCrypto is a mock of Crypto interface.
type MockCrypto struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoMockRecorder
	isgomock struct{}
}

// MockCryptoMockRecorder is the mock recorder for MockCrypto.
type MockCryptoMockRecorder struct {
	mock *MockCrypto
}

// NewMockCrypto creates a new mock instance.
func NewMockCrypto(ctrl *gomock.Controller) *MockCrypto {
	mock := &MockCrypto{ctrl: ctrl}
	mock.recorder = &MockCryptoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrypto) EXPECT() *MockCryptoMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCrypto) Decrypt(encrypted string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", encrypted)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCryptoMockRecorder) Decrypt(encrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCrypto)(nil).Decrypt), encrypted)
}

// Encrypt mocks base method.
func (m *MockCrypto) Encrypt(plaintext []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCryptoMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCrypto)(nil).Encrypt), plaintext)
}

// VerifySignature mocks base method.
func (m *MockCrypto) VerifySignature(signature, timestamp, nonce, msgEncrypt string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySignature", signature, timestamp, nonce, msgEncrypt)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifySignature indicates an expected call of VerifySignature.
func (mr *MockCryptoMockRecorder) VerifySignature(signature, timestamp, nonce, msgEncrypt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySignature", reflect.TypeOf((*MockCrypto)(nil).VerifySignature), signature, timestamp, nonce, msgEncrypt)
}
