// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wework/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/wework/service.go -destination=internal/wework/mock_service.go -package=wework
//

// Package wework is a generated GoMock package.
package wework

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleCallback mocks base method.
func (m *MockService) HandleCallback(ctx context.Context, q CallbackQuery, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, q, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockServiceMockRecorder) HandleCallback(ctx, q, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockService)(nil).HandleCallback), ctx, q, body)
}

// VerifyURL mocks base method.
func (m *MockService) VerifyURL(ctx context.Context, q CallbackQuery) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyURL", ctx, q)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyURL indicates an expected call of VerifyURL.
func (mr *MockServiceMockRecorder) VerifyURL(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyURL", reflect.TypeOf((*MockService)(nil).VerifyURL), ctx, q)
}
